### ISSUE TITLE
Compile error on HEAD: `Option<NaiveDate>::to_string()` in src/output/data.rs:84

### ISSUE THREAD

**Issue by Delibread0601** [Polymarket/polymarket-cli#65]
Building latest `main` (4b5a749) fails with `cargo install --path .`:

```
error[E0599]: `std::option::Option<NaiveDate>` doesn't implement `std::fmt::Display`
  --> src/output/data.rs:84:48
   |
84 |                         "end_date": p.end_date.to_string(),
   |                                                ^^^^^^^^^ method cannot be called on `std::option::Option<NaiveDate>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `std::option::Option<NaiveDate>: std::fmt::Display`
           which is required by `std::option::Option<NaiveDate>: ToString`
```

`p.end_date` is `Option<NaiveDate>`, so `.to_string()` must be mapped over the `Option` — e.g. `.map(|d| d.to_string()).unwrap_or_default()`, or emit `null` via `serde_json::Value::Null` when absent.

Introduced in #60 (commit adding the closed-positions JSON output block). Last compilable commit: `e1c021f`.

## Environment
- macOS 15.x
- `rustc 1.90.0 (1159e78c4 2025-09-14)` stable
- `cargo install --path .`

**Comment by Marinell0** [comment]
I got it fixed by changing line 84:

`"end_date": p.end_date.to_string(),`

to

`"end_date": p.end_date.map(|d| d.to_string()).unwrap_or_default(),`

But I don't know if it is the intended value to return

**Comment by 3ltrashpanda** [comment]
The Cargo.toml allows any 0.4.x SDK version, and 0.4.4 changes this field to Option<NaiveDate>. If you update dependencies later, this same area will need an adjustment or the dependency should be pinned more tightly.

**Comment by neofutur** [comment]
EDIT : downgrading rust is useless, but the temporary fix offered by @Marinell0  woked here.

> changing line 84:
> "end_date": p.end_date.to_string(), 
> to
> "end_date": p.end_date.map(|d| d.to_string()).unwrap_or_default(),
> 

same problem here using rust-1.91 :
should I downgrade to rust 1.85 ? 
 
error[E0599]: `std::option::Option<NaiveDate>` doesn't implement `std::fmt::Display`
  --> src/output/data.rs:84:48
   |
84 |                         "end_date": p.end_date.to_string(),
   |                                                ^^^^^^^^^ method cannot be called on `std::option::Option<NaiveDate>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `std::option::Option<NaiveDate>: std::fmt::Display`
           which is required by `std::option::Option<NaiveDate>: ToString`
note: the method `to_string` exists on the type `NaiveDate`
  --> /build/rustc-1.91-1HxzaB/rustc-1.91-1.91.1+dfsg~24.04/library/alloc/src/string.rs:2785:5
help: consider using `Option::expect` to unwrap the `NaiveDate` value, panicking if the value is an `Option::None`
   |
84 |                         "end_date": p.end_date.expect("REASON").to_string(),
   |                                               +++++++++++++++++
