### PR TITLE
fix: handle Option<NaiveDate> when serializing end_date

### LINKED ISSUE #65: Compile error on HEAD: `Option<NaiveDate>::to_string()` in src/output/data.rs:84
Building latest `main` (4b5a749) fails with `cargo install --path .`:

```
error[E0599]: `std::option::Option<NaiveDate>` doesn't implement `std::fmt::Display`
  --> src/output/data.rs:84:48
   |
84 |                         "end_date": p.end_date.to_string(),
   |                                                ^^^^^^^^^ method cannot be called on `std::option::Option<NaiveDate>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `std::option::Option<NaiveDate>: std::fmt::Display`
           which is required by `std::option::Option<NaiveDate>: ToString`
```

`p.end_date` is `Option<NaiveDate>`, so `.to_string()` must be mapped over the `Option` — e.g. `.map(|d| d.to_string()).unwrap_or_default()`, or emit `null` via `serde_json::Value::Null` when absent.

Introduced in #60 (commit adding the closed-positions JSON output block). Last compilable commit: `e1c021f`.

## Environment
- macOS 15.x
- `rustc 1.90.0 (1159e78c4 2025-09-14)` stable
- `cargo install --path .`

### PR DESCRIPTION
**Pull request by MackDing**
Fixes #65

`p.end_date` is `Option<NaiveDate>` so calling `.to_string()` directly fails to compile on stable Rust.

Verified with `cargo check` (0 errors).

---

> [!NOTE]
> **Low Risk**
> Small, localized change to JSON formatting for a single field; main impact is that missing `end_date` now serializes as `null` instead of failing to compile.
> 
> **Overview**
> Fixes JSON serialization for `Position.end_date` in `print_positions` by converting it with `Option::map` instead of calling `.to_string()` directly.
> 
> This makes `end_date` emit as either a string date or `null` in the JSON output and restores compilation on stable Rust when `end_date` is `Option<NaiveDate>`.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 85494cc5ee8310a85071659e595ae77677fb7a5d. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by MackDing** [comment]
Quick follow-up: this PR appears mergeable from my side; the remaining blocker looks like required maintainer review. Happy to adjust if you prefer a different approach.

**Comment by MackDing** [comment]
Checking in on this PR. It is still open and appears to be waiting on maintainer review.

I am happy to adjust the scope or add verification details if that would make review easier.

**Comment by Ivoneybtc** [comment]
ok, lets go!!!
